//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSWithFriendManagement.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cs.uoregon.edu/", ConfigurationName="Server.GPSwfriends")]
    public interface GPSwfriends {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getGroupRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getGroupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getGroupResponse getGroup(GPSWithFriendManagement.Server.getGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getGroupRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getGroupResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupResponse> getGroupAsync(GPSWithFriendManagement.Server.getGroupRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/authenticateRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/authenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.authenticateResponse authenticate(GPSWithFriendManagement.Server.authenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/authenticateRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/authenticateResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.authenticateResponse> authenticateAsync(GPSWithFriendManagement.Server.authenticateRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/registerRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.registerResponse register(GPSWithFriendManagement.Server.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/registerRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/registerResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.registerResponse> registerAsync(GPSWithFriendManagement.Server.registerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getLocationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getLocationResponse getLocation(GPSWithFriendManagement.Server.getLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getLocationResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getLocationResponse> getLocationAsync(GPSWithFriendManagement.Server.getLocationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getMembersRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getMembersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getMembersResponse getMembers(GPSWithFriendManagement.Server.getMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getMembersRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getMembersResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getMembersResponse> getMembersAsync(GPSWithFriendManagement.Server.getMembersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/createGroupRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/createGroupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.createGroupResponse createGroup(GPSWithFriendManagement.Server.createGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/createGroupRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/createGroupResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.createGroupResponse> createGroupAsync(GPSWithFriendManagement.Server.createGroupRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getGroupsRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getGroupsResponse getGroups(GPSWithFriendManagement.Server.getGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getGroupsRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getGroupsResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupsResponse> getGroupsAsync(GPSWithFriendManagement.Server.getGroupsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getUserRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getUserResponse getUser(GPSWithFriendManagement.Server.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getUserRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getUserResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserResponse> getUserAsync(GPSWithFriendManagement.Server.getUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/setLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/setLocationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.setLocationResponse setLocation(GPSWithFriendManagement.Server.setLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/setLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/setLocationResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.setLocationResponse> setLocationAsync(GPSWithFriendManagement.Server.setLocationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getHistoryRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getHistoryResponse getHistory(GPSWithFriendManagement.Server.getHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getHistoryRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getHistoryResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getHistoryResponse> getHistoryAsync(GPSWithFriendManagement.Server.getHistoryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getUserByIDRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getUserByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.getUserByIDResponse getUserByID(GPSWithFriendManagement.Server.getUserByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/getUserByIDRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getUserByIDResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserByIDResponse> getUserByIDAsync(GPSWithFriendManagement.Server.getUserByIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/addMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/addMemberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.addMemberResponse addMember(GPSWithFriendManagement.Server.addMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/addMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/addMemberResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.addMemberResponse> addMemberAsync(GPSWithFriendManagement.Server.addMemberRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/removeMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/removeMemberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GPSWithFriendManagement.Server.removeMemberResponse removeMember(GPSWithFriendManagement.Server.removeMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cs.uoregon.edu/GPSwfriends/removeMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/removeMemberResponse")]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.removeMemberResponse> removeMemberAsync(GPSWithFriendManagement.Server.removeMemberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class group : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user[] usersField;
        
        private string nameField;
        
        private int gidField;
        
        private int ownerField;
        
        private string date_createdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("users", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public user[] users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("users");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gid {
            get {
                return this.gidField;
            }
            set {
                this.gidField = value;
                this.RaisePropertyChanged("gid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string date_created {
            get {
                return this.date_createdField;
            }
            set {
                this.date_createdField = value;
                this.RaisePropertyChanged("date_created");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uidField;
        
        private string fNameField;
        
        private string lNameField;
        
        private string emailField;
        
        private location lastLocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
                this.RaisePropertyChanged("fName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lName {
            get {
                return this.lNameField;
            }
            set {
                this.lNameField = value;
                this.RaisePropertyChanged("lName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public location lastLoc {
            get {
                return this.lastLocField;
            }
            set {
                this.lastLocField = value;
                this.RaisePropertyChanged("lastLoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uidField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class userStatus : status {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroup", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gid;
        
        public getGroupRequest() {
        }
        
        public getGroupRequest(int gid) {
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.group @return;
        
        public getGroupResponse() {
        }
        
        public getGroupResponse(GPSWithFriendManagement.Server.group @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticate", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class authenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public authenticateRequest() {
        }
        
        public authenticateRequest(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.userStatus @return;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(GPSWithFriendManagement.Server.userStatus @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lname;
        
        public registerRequest() {
        }
        
        public registerRequest(string email, string password, string fname, string lname) {
            this.email = email;
            this.password = password;
            this.fname = fname;
            this.lname = lname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.status @return;
        
        public registerResponse() {
        }
        
        public registerResponse(GPSWithFriendManagement.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocation", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        public getLocationRequest() {
        }
        
        public getLocationRequest(int uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocationResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.location @return;
        
        public getLocationResponse() {
        }
        
        public getLocationResponse(GPSWithFriendManagement.Server.location @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMembers", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gid;
        
        public getMembersRequest() {
        }
        
        public getMembersRequest(int gid) {
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMembersResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GPSWithFriendManagement.Server.user[] @return;
        
        public getMembersResponse() {
        }
        
        public getMembersResponse(GPSWithFriendManagement.Server.user[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGroup", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class createGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("uids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] uids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public createGroupRequest() {
        }
        
        public createGroupRequest(System.Nullable<int>[] uids, int owner, string name) {
            this.uids = uids;
            this.owner = owner;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGroupResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class createGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.status @return;
        
        public createGroupResponse() {
        }
        
        public createGroupResponse(GPSWithFriendManagement.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroups", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        public getGroupsRequest() {
        }
        
        public getGroupsRequest(int uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupsResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GPSWithFriendManagement.Server.group[] @return;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(GPSWithFriendManagement.Server.group[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public getUserRequest() {
        }
        
        public getUserRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.user @return;
        
        public getUserResponse() {
        }
        
        public getUserResponse(GPSWithFriendManagement.Server.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLocation", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class setLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double latitude;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double longitude;
        
        public setLocationRequest() {
        }
        
        public setLocationRequest(int uid, double latitude, double longitude) {
            this.uid = uid;
            this.latitude = latitude;
            this.longitude = longitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLocationResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class setLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.status @return;
        
        public setLocationResponse() {
        }
        
        public setLocationResponse(GPSWithFriendManagement.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHistory", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number;
        
        public getHistoryRequest() {
        }
        
        public getHistoryRequest(int uid, int number) {
            this.uid = uid;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHistoryResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GPSWithFriendManagement.Server.location[] @return;
        
        public getHistoryResponse() {
        }
        
        public getHistoryResponse(GPSWithFriendManagement.Server.location[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByID", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getUserByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        public getUserByIDRequest() {
        }
        
        public getUserByIDRequest(int uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByIDResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getUserByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.user @return;
        
        public getUserByIDResponse() {
        }
        
        public getUserByIDResponse(GPSWithFriendManagement.Server.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMember", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class addMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gid;
        
        public addMemberRequest() {
        }
        
        public addMemberRequest(int uid, int gid) {
            this.uid = uid;
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMemberResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class addMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.status @return;
        
        public addMemberResponse() {
        }
        
        public addMemberResponse(GPSWithFriendManagement.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeMember", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class removeMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gid;
        
        public removeMemberRequest() {
        }
        
        public removeMemberRequest(int uid, int gid) {
            this.uid = uid;
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeMemberResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class removeMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriendManagement.Server.status @return;
        
        public removeMemberResponse() {
        }
        
        public removeMemberResponse(GPSWithFriendManagement.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPSwfriendsChannel : GPSWithFriendManagement.Server.GPSwfriends, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPSwfriendsClient : System.ServiceModel.ClientBase<GPSWithFriendManagement.Server.GPSwfriends>, GPSWithFriendManagement.Server.GPSwfriends {
        
        public GPSwfriendsClient() {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPSwfriendsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getGroupResponse GPSWithFriendManagement.Server.GPSwfriends.getGroup(GPSWithFriendManagement.Server.getGroupRequest request) {
            return base.Channel.getGroup(request);
        }
        
        public GPSWithFriendManagement.Server.group getGroup(int gid) {
            GPSWithFriendManagement.Server.getGroupRequest inValue = new GPSWithFriendManagement.Server.getGroupRequest();
            inValue.gid = gid;
            GPSWithFriendManagement.Server.getGroupResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getGroup(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupResponse> GPSWithFriendManagement.Server.GPSwfriends.getGroupAsync(GPSWithFriendManagement.Server.getGroupRequest request) {
            return base.Channel.getGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupResponse> getGroupAsync(int gid) {
            GPSWithFriendManagement.Server.getGroupRequest inValue = new GPSWithFriendManagement.Server.getGroupRequest();
            inValue.gid = gid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.authenticateResponse GPSWithFriendManagement.Server.GPSwfriends.authenticate(GPSWithFriendManagement.Server.authenticateRequest request) {
            return base.Channel.authenticate(request);
        }
        
        public GPSWithFriendManagement.Server.userStatus authenticate(string email, string password) {
            GPSWithFriendManagement.Server.authenticateRequest inValue = new GPSWithFriendManagement.Server.authenticateRequest();
            inValue.email = email;
            inValue.password = password;
            GPSWithFriendManagement.Server.authenticateResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).authenticate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.authenticateResponse> GPSWithFriendManagement.Server.GPSwfriends.authenticateAsync(GPSWithFriendManagement.Server.authenticateRequest request) {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.authenticateResponse> authenticateAsync(string email, string password) {
            GPSWithFriendManagement.Server.authenticateRequest inValue = new GPSWithFriendManagement.Server.authenticateRequest();
            inValue.email = email;
            inValue.password = password;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).authenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.registerResponse GPSWithFriendManagement.Server.GPSwfriends.register(GPSWithFriendManagement.Server.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public GPSWithFriendManagement.Server.status register(string email, string password, string fname, string lname) {
            GPSWithFriendManagement.Server.registerRequest inValue = new GPSWithFriendManagement.Server.registerRequest();
            inValue.email = email;
            inValue.password = password;
            inValue.fname = fname;
            inValue.lname = lname;
            GPSWithFriendManagement.Server.registerResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).register(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.registerResponse> GPSWithFriendManagement.Server.GPSwfriends.registerAsync(GPSWithFriendManagement.Server.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.registerResponse> registerAsync(string email, string password, string fname, string lname) {
            GPSWithFriendManagement.Server.registerRequest inValue = new GPSWithFriendManagement.Server.registerRequest();
            inValue.email = email;
            inValue.password = password;
            inValue.fname = fname;
            inValue.lname = lname;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getLocationResponse GPSWithFriendManagement.Server.GPSwfriends.getLocation(GPSWithFriendManagement.Server.getLocationRequest request) {
            return base.Channel.getLocation(request);
        }
        
        public GPSWithFriendManagement.Server.location getLocation(int uid) {
            GPSWithFriendManagement.Server.getLocationRequest inValue = new GPSWithFriendManagement.Server.getLocationRequest();
            inValue.uid = uid;
            GPSWithFriendManagement.Server.getLocationResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getLocation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getLocationResponse> GPSWithFriendManagement.Server.GPSwfriends.getLocationAsync(GPSWithFriendManagement.Server.getLocationRequest request) {
            return base.Channel.getLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getLocationResponse> getLocationAsync(int uid) {
            GPSWithFriendManagement.Server.getLocationRequest inValue = new GPSWithFriendManagement.Server.getLocationRequest();
            inValue.uid = uid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getMembersResponse GPSWithFriendManagement.Server.GPSwfriends.getMembers(GPSWithFriendManagement.Server.getMembersRequest request) {
            return base.Channel.getMembers(request);
        }
        
        public GPSWithFriendManagement.Server.user[] getMembers(int gid) {
            GPSWithFriendManagement.Server.getMembersRequest inValue = new GPSWithFriendManagement.Server.getMembersRequest();
            inValue.gid = gid;
            GPSWithFriendManagement.Server.getMembersResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getMembers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getMembersResponse> GPSWithFriendManagement.Server.GPSwfriends.getMembersAsync(GPSWithFriendManagement.Server.getMembersRequest request) {
            return base.Channel.getMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getMembersResponse> getMembersAsync(int gid) {
            GPSWithFriendManagement.Server.getMembersRequest inValue = new GPSWithFriendManagement.Server.getMembersRequest();
            inValue.gid = gid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getMembersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.createGroupResponse GPSWithFriendManagement.Server.GPSwfriends.createGroup(GPSWithFriendManagement.Server.createGroupRequest request) {
            return base.Channel.createGroup(request);
        }
        
        public GPSWithFriendManagement.Server.status createGroup(System.Nullable<int>[] uids, int owner, string name) {
            GPSWithFriendManagement.Server.createGroupRequest inValue = new GPSWithFriendManagement.Server.createGroupRequest();
            inValue.uids = uids;
            inValue.owner = owner;
            inValue.name = name;
            GPSWithFriendManagement.Server.createGroupResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).createGroup(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.createGroupResponse> GPSWithFriendManagement.Server.GPSwfriends.createGroupAsync(GPSWithFriendManagement.Server.createGroupRequest request) {
            return base.Channel.createGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.createGroupResponse> createGroupAsync(System.Nullable<int>[] uids, int owner, string name) {
            GPSWithFriendManagement.Server.createGroupRequest inValue = new GPSWithFriendManagement.Server.createGroupRequest();
            inValue.uids = uids;
            inValue.owner = owner;
            inValue.name = name;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).createGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getGroupsResponse GPSWithFriendManagement.Server.GPSwfriends.getGroups(GPSWithFriendManagement.Server.getGroupsRequest request) {
            return base.Channel.getGroups(request);
        }
        
        public GPSWithFriendManagement.Server.group[] getGroups(int uid) {
            GPSWithFriendManagement.Server.getGroupsRequest inValue = new GPSWithFriendManagement.Server.getGroupsRequest();
            inValue.uid = uid;
            GPSWithFriendManagement.Server.getGroupsResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getGroups(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupsResponse> GPSWithFriendManagement.Server.GPSwfriends.getGroupsAsync(GPSWithFriendManagement.Server.getGroupsRequest request) {
            return base.Channel.getGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getGroupsResponse> getGroupsAsync(int uid) {
            GPSWithFriendManagement.Server.getGroupsRequest inValue = new GPSWithFriendManagement.Server.getGroupsRequest();
            inValue.uid = uid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getUserResponse GPSWithFriendManagement.Server.GPSwfriends.getUser(GPSWithFriendManagement.Server.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public GPSWithFriendManagement.Server.user getUser(string email) {
            GPSWithFriendManagement.Server.getUserRequest inValue = new GPSWithFriendManagement.Server.getUserRequest();
            inValue.email = email;
            GPSWithFriendManagement.Server.getUserResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserResponse> GPSWithFriendManagement.Server.GPSwfriends.getUserAsync(GPSWithFriendManagement.Server.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserResponse> getUserAsync(string email) {
            GPSWithFriendManagement.Server.getUserRequest inValue = new GPSWithFriendManagement.Server.getUserRequest();
            inValue.email = email;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.setLocationResponse GPSWithFriendManagement.Server.GPSwfriends.setLocation(GPSWithFriendManagement.Server.setLocationRequest request) {
            return base.Channel.setLocation(request);
        }
        
        public GPSWithFriendManagement.Server.status setLocation(int uid, double latitude, double longitude) {
            GPSWithFriendManagement.Server.setLocationRequest inValue = new GPSWithFriendManagement.Server.setLocationRequest();
            inValue.uid = uid;
            inValue.latitude = latitude;
            inValue.longitude = longitude;
            GPSWithFriendManagement.Server.setLocationResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).setLocation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.setLocationResponse> GPSWithFriendManagement.Server.GPSwfriends.setLocationAsync(GPSWithFriendManagement.Server.setLocationRequest request) {
            return base.Channel.setLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.setLocationResponse> setLocationAsync(int uid, double latitude, double longitude) {
            GPSWithFriendManagement.Server.setLocationRequest inValue = new GPSWithFriendManagement.Server.setLocationRequest();
            inValue.uid = uid;
            inValue.latitude = latitude;
            inValue.longitude = longitude;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).setLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getHistoryResponse GPSWithFriendManagement.Server.GPSwfriends.getHistory(GPSWithFriendManagement.Server.getHistoryRequest request) {
            return base.Channel.getHistory(request);
        }
        
        public GPSWithFriendManagement.Server.location[] getHistory(int uid, int number) {
            GPSWithFriendManagement.Server.getHistoryRequest inValue = new GPSWithFriendManagement.Server.getHistoryRequest();
            inValue.uid = uid;
            inValue.number = number;
            GPSWithFriendManagement.Server.getHistoryResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getHistory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getHistoryResponse> GPSWithFriendManagement.Server.GPSwfriends.getHistoryAsync(GPSWithFriendManagement.Server.getHistoryRequest request) {
            return base.Channel.getHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getHistoryResponse> getHistoryAsync(int uid, int number) {
            GPSWithFriendManagement.Server.getHistoryRequest inValue = new GPSWithFriendManagement.Server.getHistoryRequest();
            inValue.uid = uid;
            inValue.number = number;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.getUserByIDResponse GPSWithFriendManagement.Server.GPSwfriends.getUserByID(GPSWithFriendManagement.Server.getUserByIDRequest request) {
            return base.Channel.getUserByID(request);
        }
        
        public GPSWithFriendManagement.Server.user getUserByID(int uid) {
            GPSWithFriendManagement.Server.getUserByIDRequest inValue = new GPSWithFriendManagement.Server.getUserByIDRequest();
            inValue.uid = uid;
            GPSWithFriendManagement.Server.getUserByIDResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getUserByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserByIDResponse> GPSWithFriendManagement.Server.GPSwfriends.getUserByIDAsync(GPSWithFriendManagement.Server.getUserByIDRequest request) {
            return base.Channel.getUserByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.getUserByIDResponse> getUserByIDAsync(int uid) {
            GPSWithFriendManagement.Server.getUserByIDRequest inValue = new GPSWithFriendManagement.Server.getUserByIDRequest();
            inValue.uid = uid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).getUserByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.addMemberResponse GPSWithFriendManagement.Server.GPSwfriends.addMember(GPSWithFriendManagement.Server.addMemberRequest request) {
            return base.Channel.addMember(request);
        }
        
        public GPSWithFriendManagement.Server.status addMember(int uid, int gid) {
            GPSWithFriendManagement.Server.addMemberRequest inValue = new GPSWithFriendManagement.Server.addMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            GPSWithFriendManagement.Server.addMemberResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).addMember(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.addMemberResponse> GPSWithFriendManagement.Server.GPSwfriends.addMemberAsync(GPSWithFriendManagement.Server.addMemberRequest request) {
            return base.Channel.addMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.addMemberResponse> addMemberAsync(int uid, int gid) {
            GPSWithFriendManagement.Server.addMemberRequest inValue = new GPSWithFriendManagement.Server.addMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).addMemberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriendManagement.Server.removeMemberResponse GPSWithFriendManagement.Server.GPSwfriends.removeMember(GPSWithFriendManagement.Server.removeMemberRequest request) {
            return base.Channel.removeMember(request);
        }
        
        public GPSWithFriendManagement.Server.status removeMember(int uid, int gid) {
            GPSWithFriendManagement.Server.removeMemberRequest inValue = new GPSWithFriendManagement.Server.removeMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            GPSWithFriendManagement.Server.removeMemberResponse retVal = ((GPSWithFriendManagement.Server.GPSwfriends)(this)).removeMember(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPSWithFriendManagement.Server.removeMemberResponse> GPSWithFriendManagement.Server.GPSwfriends.removeMemberAsync(GPSWithFriendManagement.Server.removeMemberRequest request) {
            return base.Channel.removeMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPSWithFriendManagement.Server.removeMemberResponse> removeMemberAsync(int uid, int gid) {
            GPSWithFriendManagement.Server.removeMemberRequest inValue = new GPSWithFriendManagement.Server.removeMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            return ((GPSWithFriendManagement.Server.GPSwfriends)(this)).removeMemberAsync(inValue);
        }
    }
}
