//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace HW2_WS_MobileClient.StuInfoDBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StuInfoDBService.StuInfoWebServiceSoap")]
    public interface StuInfoWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStudentName", ReplyAction="*")]
        System.IAsyncResult BeginGetStudentName(HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse EndGetStudentName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStudentGender", ReplyAction="*")]
        System.IAsyncResult BeginGetStudentGender(HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse EndGetStudentGender(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStudentMajor", ReplyAction="*")]
        System.IAsyncResult BeginGetStudentMajor(HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse EndGetStudentMajor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStudentEmail", ReplyAction="*")]
        System.IAsyncResult BeginGetStudentEmail(HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse EndGetStudentEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DeleteStudentInfo", ReplyAction="*")]
        System.IAsyncResult BeginDeleteStudentInfo(HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse EndDeleteStudentInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InsertStudentInfo", ReplyAction="*")]
        System.IAsyncResult BeginInsertStudentInfo(HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse EndInsertStudentInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateStudentInfo", ReplyAction="*")]
        System.IAsyncResult BeginUpdateStudentInfo(HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse EndUpdateStudentInfo(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentName", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequestBody Body;
        
        public GetStudentNameRequest() {
        }
        
        public GetStudentNameRequest(HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_No;
        
        public GetStudentNameRequestBody() {
        }
        
        public GetStudentNameRequestBody(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponseBody Body;
        
        public GetStudentNameResponse() {
        }
        
        public GetStudentNameResponse(HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentNameResult;
        
        public GetStudentNameResponseBody() {
        }
        
        public GetStudentNameResponseBody(string GetStudentNameResult) {
            this.GetStudentNameResult = GetStudentNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentGender", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequestBody Body;
        
        public GetStudentGenderRequest() {
        }
        
        public GetStudentGenderRequest(HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentGenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_No;
        
        public GetStudentGenderRequestBody() {
        }
        
        public GetStudentGenderRequestBody(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentGenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponseBody Body;
        
        public GetStudentGenderResponse() {
        }
        
        public GetStudentGenderResponse(HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentGenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentGenderResult;
        
        public GetStudentGenderResponseBody() {
        }
        
        public GetStudentGenderResponseBody(string GetStudentGenderResult) {
            this.GetStudentGenderResult = GetStudentGenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentMajorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentMajor", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequestBody Body;
        
        public GetStudentMajorRequest() {
        }
        
        public GetStudentMajorRequest(HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentMajorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_No;
        
        public GetStudentMajorRequestBody() {
        }
        
        public GetStudentMajorRequestBody(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentMajorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentMajorResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponseBody Body;
        
        public GetStudentMajorResponse() {
        }
        
        public GetStudentMajorResponse(HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentMajorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentMajorResult;
        
        public GetStudentMajorResponseBody() {
        }
        
        public GetStudentMajorResponseBody(string GetStudentMajorResult) {
            this.GetStudentMajorResult = GetStudentMajorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentEmail", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequestBody Body;
        
        public GetStudentEmailRequest() {
        }
        
        public GetStudentEmailRequest(HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_No;
        
        public GetStudentEmailRequestBody() {
        }
        
        public GetStudentEmailRequestBody(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponseBody Body;
        
        public GetStudentEmailResponse() {
        }
        
        public GetStudentEmailResponse(HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentEmailResult;
        
        public GetStudentEmailResponseBody() {
        }
        
        public GetStudentEmailResponseBody(string GetStudentEmailResult) {
            this.GetStudentEmailResult = GetStudentEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudentInfo", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequestBody Body;
        
        public DeleteStudentInfoRequest() {
        }
        
        public DeleteStudentInfoRequest(HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_No;
        
        public DeleteStudentInfoRequestBody() {
        }
        
        public DeleteStudentInfoRequestBody(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudentInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponseBody Body;
        
        public DeleteStudentInfoResponse() {
        }
        
        public DeleteStudentInfoResponse(HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteStudentInfoResult;
        
        public DeleteStudentInfoResponseBody() {
        }
        
        public DeleteStudentInfoResponseBody(string DeleteStudentInfoResult) {
            this.DeleteStudentInfoResult = DeleteStudentInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudentInfo", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequestBody Body;
        
        public InsertStudentInfoRequest() {
        }
        
        public InsertStudentInfoRequest(HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStudentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Info;
        
        public InsertStudentInfoRequestBody() {
        }
        
        public InsertStudentInfoRequestBody(string Info) {
            this.Info = Info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudentInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponseBody Body;
        
        public InsertStudentInfoResponse() {
        }
        
        public InsertStudentInfoResponse(HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStudentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertStudentInfoResult;
        
        public InsertStudentInfoResponseBody() {
        }
        
        public InsertStudentInfoResponseBody(string InsertStudentInfoResult) {
            this.InsertStudentInfoResult = InsertStudentInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentInfo", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequestBody Body;
        
        public UpdateStudentInfoRequest() {
        }
        
        public UpdateStudentInfoRequest(HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Info;
        
        public UpdateStudentInfoRequestBody() {
        }
        
        public UpdateStudentInfoRequestBody(string Info) {
            this.Info = Info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponseBody Body;
        
        public UpdateStudentInfoResponse() {
        }
        
        public UpdateStudentInfoResponse(HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStudentInfoResult;
        
        public UpdateStudentInfoResponseBody() {
        }
        
        public UpdateStudentInfoResponseBody(string UpdateStudentInfoResult) {
            this.UpdateStudentInfoResult = UpdateStudentInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StuInfoWebServiceSoapChannel : HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentGenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentGenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentMajorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentMajorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StuInfoWebServiceSoapClient : System.ServiceModel.ClientBase<HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap>, HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap {
        
        private BeginOperationDelegate onBeginGetStudentNameDelegate;
        
        private EndOperationDelegate onEndGetStudentNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentGenderDelegate;
        
        private EndOperationDelegate onEndGetStudentGenderDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentGenderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentMajorDelegate;
        
        private EndOperationDelegate onEndGetStudentMajorDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentMajorCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentEmailDelegate;
        
        private EndOperationDelegate onEndGetStudentEmailDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteStudentInfoDelegate;
        
        private EndOperationDelegate onEndDeleteStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertStudentInfoDelegate;
        
        private EndOperationDelegate onEndInsertStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onInsertStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateStudentInfoDelegate;
        
        private EndOperationDelegate onEndUpdateStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public StuInfoWebServiceSoapClient() {
        }
        
        public StuInfoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StuInfoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuInfoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuInfoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetStudentNameCompletedEventArgs> GetStudentNameCompleted;
        
        public event System.EventHandler<GetStudentGenderCompletedEventArgs> GetStudentGenderCompleted;
        
        public event System.EventHandler<GetStudentMajorCompletedEventArgs> GetStudentMajorCompleted;
        
        public event System.EventHandler<GetStudentEmailCompletedEventArgs> GetStudentEmailCompleted;
        
        public event System.EventHandler<DeleteStudentInfoCompletedEventArgs> DeleteStudentInfoCompleted;
        
        public event System.EventHandler<InsertStudentInfoCompletedEventArgs> InsertStudentInfoCompleted;
        
        public event System.EventHandler<UpdateStudentInfoCompletedEventArgs> UpdateStudentInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginGetStudentName(HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentName(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequestBody();
            inValue.Body.ID_No = ID_No;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginGetStudentName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndGetStudentName(System.IAsyncResult result) {
            return base.Channel.EndGetStudentName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentName(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndGetStudentName(result);
            return retVal.Body.GetStudentNameResult;
        }
        
        private System.IAsyncResult OnBeginGetStudentName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentName(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentName(System.IAsyncResult result) {
            string retVal = this.EndGetStudentName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentNameCompleted(object state) {
            if ((this.GetStudentNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentNameCompleted(this, new GetStudentNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentNameAsync(string ID_No) {
            this.GetStudentNameAsync(ID_No, null);
        }
        
        public void GetStudentNameAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentNameDelegate == null)) {
                this.onBeginGetStudentNameDelegate = new BeginOperationDelegate(this.OnBeginGetStudentName);
            }
            if ((this.onEndGetStudentNameDelegate == null)) {
                this.onEndGetStudentNameDelegate = new EndOperationDelegate(this.OnEndGetStudentName);
            }
            if ((this.onGetStudentNameCompletedDelegate == null)) {
                this.onGetStudentNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentNameDelegate, new object[] {
                        ID_No}, this.onEndGetStudentNameDelegate, this.onGetStudentNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginGetStudentGender(HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentGender(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentGender(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequestBody();
            inValue.Body.ID_No = ID_No;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginGetStudentGender(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndGetStudentGender(System.IAsyncResult result) {
            return base.Channel.EndGetStudentGender(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentGender(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndGetStudentGender(result);
            return retVal.Body.GetStudentGenderResult;
        }
        
        private System.IAsyncResult OnBeginGetStudentGender(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentGender(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentGender(System.IAsyncResult result) {
            string retVal = this.EndGetStudentGender(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentGenderCompleted(object state) {
            if ((this.GetStudentGenderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentGenderCompleted(this, new GetStudentGenderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentGenderAsync(string ID_No) {
            this.GetStudentGenderAsync(ID_No, null);
        }
        
        public void GetStudentGenderAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentGenderDelegate == null)) {
                this.onBeginGetStudentGenderDelegate = new BeginOperationDelegate(this.OnBeginGetStudentGender);
            }
            if ((this.onEndGetStudentGenderDelegate == null)) {
                this.onEndGetStudentGenderDelegate = new EndOperationDelegate(this.OnEndGetStudentGender);
            }
            if ((this.onGetStudentGenderCompletedDelegate == null)) {
                this.onGetStudentGenderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentGenderCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentGenderDelegate, new object[] {
                        ID_No}, this.onEndGetStudentGenderDelegate, this.onGetStudentGenderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginGetStudentMajor(HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentMajor(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentMajor(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequestBody();
            inValue.Body.ID_No = ID_No;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginGetStudentMajor(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndGetStudentMajor(System.IAsyncResult result) {
            return base.Channel.EndGetStudentMajor(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentMajor(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndGetStudentMajor(result);
            return retVal.Body.GetStudentMajorResult;
        }
        
        private System.IAsyncResult OnBeginGetStudentMajor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentMajor(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentMajor(System.IAsyncResult result) {
            string retVal = this.EndGetStudentMajor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentMajorCompleted(object state) {
            if ((this.GetStudentMajorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentMajorCompleted(this, new GetStudentMajorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentMajorAsync(string ID_No) {
            this.GetStudentMajorAsync(ID_No, null);
        }
        
        public void GetStudentMajorAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentMajorDelegate == null)) {
                this.onBeginGetStudentMajorDelegate = new BeginOperationDelegate(this.OnBeginGetStudentMajor);
            }
            if ((this.onEndGetStudentMajorDelegate == null)) {
                this.onEndGetStudentMajorDelegate = new EndOperationDelegate(this.OnEndGetStudentMajor);
            }
            if ((this.onGetStudentMajorCompletedDelegate == null)) {
                this.onGetStudentMajorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentMajorCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentMajorDelegate, new object[] {
                        ID_No}, this.onEndGetStudentMajorDelegate, this.onGetStudentMajorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginGetStudentEmail(HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentEmail(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentEmail(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequestBody();
            inValue.Body.ID_No = ID_No;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginGetStudentEmail(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndGetStudentEmail(System.IAsyncResult result) {
            return base.Channel.EndGetStudentEmail(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentEmail(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndGetStudentEmail(result);
            return retVal.Body.GetStudentEmailResult;
        }
        
        private System.IAsyncResult OnBeginGetStudentEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentEmail(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentEmail(System.IAsyncResult result) {
            string retVal = this.EndGetStudentEmail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentEmailCompleted(object state) {
            if ((this.GetStudentEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentEmailCompleted(this, new GetStudentEmailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentEmailAsync(string ID_No) {
            this.GetStudentEmailAsync(ID_No, null);
        }
        
        public void GetStudentEmailAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentEmailDelegate == null)) {
                this.onBeginGetStudentEmailDelegate = new BeginOperationDelegate(this.OnBeginGetStudentEmail);
            }
            if ((this.onEndGetStudentEmailDelegate == null)) {
                this.onEndGetStudentEmailDelegate = new EndOperationDelegate(this.OnEndGetStudentEmail);
            }
            if ((this.onGetStudentEmailCompletedDelegate == null)) {
                this.onGetStudentEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentEmailCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentEmailDelegate, new object[] {
                        ID_No}, this.onEndGetStudentEmailDelegate, this.onGetStudentEmailCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginDeleteStudentInfo(HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDeleteStudentInfo(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequestBody();
            inValue.Body.ID_No = ID_No;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginDeleteStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndDeleteStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndDeleteStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndDeleteStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndDeleteStudentInfo(result);
            return retVal.Body.DeleteStudentInfoResult;
        }
        
        private System.IAsyncResult OnBeginDeleteStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginDeleteStudentInfo(ID_No, callback, asyncState);
        }
        
        private object[] OnEndDeleteStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndDeleteStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteStudentInfoCompleted(object state) {
            if ((this.DeleteStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteStudentInfoCompleted(this, new DeleteStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteStudentInfoAsync(string ID_No) {
            this.DeleteStudentInfoAsync(ID_No, null);
        }
        
        public void DeleteStudentInfoAsync(string ID_No, object userState) {
            if ((this.onBeginDeleteStudentInfoDelegate == null)) {
                this.onBeginDeleteStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginDeleteStudentInfo);
            }
            if ((this.onEndDeleteStudentInfoDelegate == null)) {
                this.onEndDeleteStudentInfoDelegate = new EndOperationDelegate(this.OnEndDeleteStudentInfo);
            }
            if ((this.onDeleteStudentInfoCompletedDelegate == null)) {
                this.onDeleteStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteStudentInfoDelegate, new object[] {
                        ID_No}, this.onEndDeleteStudentInfoDelegate, this.onDeleteStudentInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginInsertStudentInfo(HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginInsertStudentInfo(string Info, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequestBody();
            inValue.Body.Info = Info;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginInsertStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndInsertStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndInsertStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndInsertStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndInsertStudentInfo(result);
            return retVal.Body.InsertStudentInfoResult;
        }
        
        private System.IAsyncResult OnBeginInsertStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Info = ((string)(inValues[0]));
            return this.BeginInsertStudentInfo(Info, callback, asyncState);
        }
        
        private object[] OnEndInsertStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndInsertStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertStudentInfoCompleted(object state) {
            if ((this.InsertStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertStudentInfoCompleted(this, new InsertStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertStudentInfoAsync(string Info) {
            this.InsertStudentInfoAsync(Info, null);
        }
        
        public void InsertStudentInfoAsync(string Info, object userState) {
            if ((this.onBeginInsertStudentInfoDelegate == null)) {
                this.onBeginInsertStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginInsertStudentInfo);
            }
            if ((this.onEndInsertStudentInfoDelegate == null)) {
                this.onEndInsertStudentInfoDelegate = new EndOperationDelegate(this.OnEndInsertStudentInfo);
            }
            if ((this.onInsertStudentInfoCompletedDelegate == null)) {
                this.onInsertStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginInsertStudentInfoDelegate, new object[] {
                        Info}, this.onEndInsertStudentInfoDelegate, this.onInsertStudentInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.BeginUpdateStudentInfo(HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateStudentInfo(string Info, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequest inValue = new HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequest();
            inValue.Body = new HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequestBody();
            inValue.Body.Info = Info;
            return ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).BeginUpdateStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap.EndUpdateStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndUpdateStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUpdateStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse retVal = ((HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap)(this)).EndUpdateStudentInfo(result);
            return retVal.Body.UpdateStudentInfoResult;
        }
        
        private System.IAsyncResult OnBeginUpdateStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Info = ((string)(inValues[0]));
            return this.BeginUpdateStudentInfo(Info, callback, asyncState);
        }
        
        private object[] OnEndUpdateStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndUpdateStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateStudentInfoCompleted(object state) {
            if ((this.UpdateStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateStudentInfoCompleted(this, new UpdateStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateStudentInfoAsync(string Info) {
            this.UpdateStudentInfoAsync(Info, null);
        }
        
        public void UpdateStudentInfoAsync(string Info, object userState) {
            if ((this.onBeginUpdateStudentInfoDelegate == null)) {
                this.onBeginUpdateStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginUpdateStudentInfo);
            }
            if ((this.onEndUpdateStudentInfoDelegate == null)) {
                this.onEndUpdateStudentInfoDelegate = new EndOperationDelegate(this.OnEndUpdateStudentInfo);
            }
            if ((this.onUpdateStudentInfoCompletedDelegate == null)) {
                this.onUpdateStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateStudentInfoDelegate, new object[] {
                        Info}, this.onEndUpdateStudentInfoDelegate, this.onUpdateStudentInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap CreateChannel() {
            return new StuInfoWebServiceSoapClientChannel(this);
        }
        
        private class StuInfoWebServiceSoapClientChannel : ChannelBase<HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap>, HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap {
            
            public StuInfoWebServiceSoapClientChannel(System.ServiceModel.ClientBase<HW2_WS_MobileClient.StuInfoDBService.StuInfoWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetStudentName(HW2_WS_MobileClient.StuInfoDBService.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentName", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse EndGetStudentName(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.GetStudentNameResponse)(base.EndInvoke("GetStudentName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentGender(HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentGender", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse EndGetStudentGender(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.GetStudentGenderResponse)(base.EndInvoke("GetStudentGender", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentMajor(HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentMajor", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse EndGetStudentMajor(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.GetStudentMajorResponse)(base.EndInvoke("GetStudentMajor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentEmail(HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentEmail", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse EndGetStudentEmail(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.GetStudentEmailResponse)(base.EndInvoke("GetStudentEmail", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteStudentInfo(HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DeleteStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse EndDeleteStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.DeleteStudentInfoResponse)(base.EndInvoke("DeleteStudentInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertStudentInfo(HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("InsertStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse EndInsertStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.InsertStudentInfoResponse)(base.EndInvoke("InsertStudentInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateStudentInfo(HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse EndUpdateStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse _result = ((HW2_WS_MobileClient.StuInfoDBService.UpdateStudentInfoResponse)(base.EndInvoke("UpdateStudentInfo", _args, result)));
                return _result;
            }
        }
    }
}
