//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace HW2_WS_MobileClient.TomcatServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://StuInfoWebService", ConfigurationName="TomcatServices.StuInfoWebServicePortType")]
    public interface StuInfoWebServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DeleteStudentInfo", ReplyAction="urn:DeleteStudentInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginDeleteStudentInfo(HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse EndDeleteStudentInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetStudentEmailAddress", ReplyAction="urn:GetStudentEmailAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetStudentEmailAddress(HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse EndGetStudentEmailAddress(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UpdateStudentInfo", ReplyAction="urn:UpdateStudentInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginUpdateStudentInfo(HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse EndUpdateStudentInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetStudentName", ReplyAction="urn:GetStudentNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetStudentName(HW2_WS_MobileClient.TomcatServices.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse EndGetStudentName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetStudentGender", ReplyAction="urn:GetStudentGenderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetStudentGender(HW2_WS_MobileClient.TomcatServices.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse EndGetStudentGender(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetStudentMajor", ReplyAction="urn:GetStudentMajorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetStudentMajor(HW2_WS_MobileClient.TomcatServices.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse EndGetStudentMajor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:InsertStudentInfo", ReplyAction="urn:InsertStudentInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginInsertStudentInfo(HW2_WS_MobileClient.TomcatServices.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse EndInsertStudentInfo(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentInfo", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class DeleteStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_No;
        
        public DeleteStudentInfoRequest() {
        }
        
        public DeleteStudentInfoRequest(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentInfoResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class DeleteStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public DeleteStudentInfoResponse() {
        }
        
        public DeleteStudentInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentEmailAddress", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentEmailAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_No;
        
        public GetStudentEmailAddressRequest() {
        }
        
        public GetStudentEmailAddressRequest(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentEmailAddressResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentEmailAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GetStudentEmailAddressResponse() {
        }
        
        public GetStudentEmailAddressResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentInfo", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class UpdateStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Info;
        
        public UpdateStudentInfoRequest() {
        }
        
        public UpdateStudentInfoRequest(string Info) {
            this.Info = Info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentInfoResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class UpdateStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public UpdateStudentInfoResponse() {
        }
        
        public UpdateStudentInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentName", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_No;
        
        public GetStudentNameRequest() {
        }
        
        public GetStudentNameRequest(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentNameResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GetStudentNameResponse() {
        }
        
        public GetStudentNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentGender", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_No;
        
        public GetStudentGenderRequest() {
        }
        
        public GetStudentGenderRequest(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentGenderResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GetStudentGenderResponse() {
        }
        
        public GetStudentGenderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentMajor", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentMajorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_No;
        
        public GetStudentMajorRequest() {
        }
        
        public GetStudentMajorRequest(string ID_No) {
            this.ID_No = ID_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentMajorResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class GetStudentMajorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GetStudentMajorResponse() {
        }
        
        public GetStudentMajorResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStudentInfo", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class InsertStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Info;
        
        public InsertStudentInfoRequest() {
        }
        
        public InsertStudentInfoRequest(string Info) {
            this.Info = Info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStudentInfoResponse", WrapperNamespace="http://StuInfoWebService", IsWrapped=true)]
    public partial class InsertStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://StuInfoWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public InsertStudentInfoResponse() {
        }
        
        public InsertStudentInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StuInfoWebServicePortTypeChannel : HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentGenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentGenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentMajorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentMajorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertStudentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertStudentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StuInfoWebServicePortTypeClient : System.ServiceModel.ClientBase<HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType>, HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType {
        
        private BeginOperationDelegate onBeginDeleteStudentInfoDelegate;
        
        private EndOperationDelegate onEndDeleteStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentEmailAddressDelegate;
        
        private EndOperationDelegate onEndGetStudentEmailAddressDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentEmailAddressCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateStudentInfoDelegate;
        
        private EndOperationDelegate onEndUpdateStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentNameDelegate;
        
        private EndOperationDelegate onEndGetStudentNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentGenderDelegate;
        
        private EndOperationDelegate onEndGetStudentGenderDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentGenderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentMajorDelegate;
        
        private EndOperationDelegate onEndGetStudentMajorDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentMajorCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertStudentInfoDelegate;
        
        private EndOperationDelegate onEndInsertStudentInfoDelegate;
        
        private System.Threading.SendOrPostCallback onInsertStudentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public StuInfoWebServicePortTypeClient() {
        }
        
        public StuInfoWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StuInfoWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuInfoWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuInfoWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DeleteStudentInfoCompletedEventArgs> DeleteStudentInfoCompleted;
        
        public event System.EventHandler<GetStudentEmailAddressCompletedEventArgs> GetStudentEmailAddressCompleted;
        
        public event System.EventHandler<UpdateStudentInfoCompletedEventArgs> UpdateStudentInfoCompleted;
        
        public event System.EventHandler<GetStudentNameCompletedEventArgs> GetStudentNameCompleted;
        
        public event System.EventHandler<GetStudentGenderCompletedEventArgs> GetStudentGenderCompleted;
        
        public event System.EventHandler<GetStudentMajorCompletedEventArgs> GetStudentMajorCompleted;
        
        public event System.EventHandler<InsertStudentInfoCompletedEventArgs> InsertStudentInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginDeleteStudentInfo(HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDeleteStudentInfo(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoRequest inValue = new HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoRequest();
            inValue.ID_No = ID_No;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginDeleteStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndDeleteStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndDeleteStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndDeleteStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndDeleteStudentInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginDeleteStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginDeleteStudentInfo(ID_No, callback, asyncState);
        }
        
        private object[] OnEndDeleteStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndDeleteStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteStudentInfoCompleted(object state) {
            if ((this.DeleteStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteStudentInfoCompleted(this, new DeleteStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteStudentInfoAsync(string ID_No) {
            this.DeleteStudentInfoAsync(ID_No, null);
        }
        
        public void DeleteStudentInfoAsync(string ID_No, object userState) {
            if ((this.onBeginDeleteStudentInfoDelegate == null)) {
                this.onBeginDeleteStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginDeleteStudentInfo);
            }
            if ((this.onEndDeleteStudentInfoDelegate == null)) {
                this.onEndDeleteStudentInfoDelegate = new EndOperationDelegate(this.OnEndDeleteStudentInfo);
            }
            if ((this.onDeleteStudentInfoCompletedDelegate == null)) {
                this.onDeleteStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteStudentInfoDelegate, new object[] {
                        ID_No}, this.onEndDeleteStudentInfoDelegate, this.onDeleteStudentInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginGetStudentEmailAddress(HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentEmailAddress(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentEmailAddress(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressRequest inValue = new HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressRequest();
            inValue.ID_No = ID_No;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginGetStudentEmailAddress(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndGetStudentEmailAddress(System.IAsyncResult result) {
            return base.Channel.EndGetStudentEmailAddress(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentEmailAddress(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndGetStudentEmailAddress(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetStudentEmailAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentEmailAddress(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentEmailAddress(System.IAsyncResult result) {
            string retVal = this.EndGetStudentEmailAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentEmailAddressCompleted(object state) {
            if ((this.GetStudentEmailAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentEmailAddressCompleted(this, new GetStudentEmailAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentEmailAddressAsync(string ID_No) {
            this.GetStudentEmailAddressAsync(ID_No, null);
        }
        
        public void GetStudentEmailAddressAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentEmailAddressDelegate == null)) {
                this.onBeginGetStudentEmailAddressDelegate = new BeginOperationDelegate(this.OnBeginGetStudentEmailAddress);
            }
            if ((this.onEndGetStudentEmailAddressDelegate == null)) {
                this.onEndGetStudentEmailAddressDelegate = new EndOperationDelegate(this.OnEndGetStudentEmailAddress);
            }
            if ((this.onGetStudentEmailAddressCompletedDelegate == null)) {
                this.onGetStudentEmailAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentEmailAddressCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentEmailAddressDelegate, new object[] {
                        ID_No}, this.onEndGetStudentEmailAddressDelegate, this.onGetStudentEmailAddressCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginUpdateStudentInfo(HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateStudentInfo(string Info, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoRequest inValue = new HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoRequest();
            inValue.Info = Info;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginUpdateStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndUpdateStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndUpdateStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUpdateStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndUpdateStudentInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginUpdateStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Info = ((string)(inValues[0]));
            return this.BeginUpdateStudentInfo(Info, callback, asyncState);
        }
        
        private object[] OnEndUpdateStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndUpdateStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateStudentInfoCompleted(object state) {
            if ((this.UpdateStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateStudentInfoCompleted(this, new UpdateStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateStudentInfoAsync(string Info) {
            this.UpdateStudentInfoAsync(Info, null);
        }
        
        public void UpdateStudentInfoAsync(string Info, object userState) {
            if ((this.onBeginUpdateStudentInfoDelegate == null)) {
                this.onBeginUpdateStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginUpdateStudentInfo);
            }
            if ((this.onEndUpdateStudentInfoDelegate == null)) {
                this.onEndUpdateStudentInfoDelegate = new EndOperationDelegate(this.OnEndUpdateStudentInfo);
            }
            if ((this.onUpdateStudentInfoCompletedDelegate == null)) {
                this.onUpdateStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateStudentInfoDelegate, new object[] {
                        Info}, this.onEndUpdateStudentInfoDelegate, this.onUpdateStudentInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginGetStudentName(HW2_WS_MobileClient.TomcatServices.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentName(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.GetStudentNameRequest inValue = new HW2_WS_MobileClient.TomcatServices.GetStudentNameRequest();
            inValue.ID_No = ID_No;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginGetStudentName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndGetStudentName(System.IAsyncResult result) {
            return base.Channel.EndGetStudentName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentName(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndGetStudentName(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetStudentName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentName(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentName(System.IAsyncResult result) {
            string retVal = this.EndGetStudentName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentNameCompleted(object state) {
            if ((this.GetStudentNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentNameCompleted(this, new GetStudentNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentNameAsync(string ID_No) {
            this.GetStudentNameAsync(ID_No, null);
        }
        
        public void GetStudentNameAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentNameDelegate == null)) {
                this.onBeginGetStudentNameDelegate = new BeginOperationDelegate(this.OnBeginGetStudentName);
            }
            if ((this.onEndGetStudentNameDelegate == null)) {
                this.onEndGetStudentNameDelegate = new EndOperationDelegate(this.OnEndGetStudentName);
            }
            if ((this.onGetStudentNameCompletedDelegate == null)) {
                this.onGetStudentNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentNameDelegate, new object[] {
                        ID_No}, this.onEndGetStudentNameDelegate, this.onGetStudentNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginGetStudentGender(HW2_WS_MobileClient.TomcatServices.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentGender(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentGender(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.GetStudentGenderRequest inValue = new HW2_WS_MobileClient.TomcatServices.GetStudentGenderRequest();
            inValue.ID_No = ID_No;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginGetStudentGender(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndGetStudentGender(System.IAsyncResult result) {
            return base.Channel.EndGetStudentGender(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentGender(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndGetStudentGender(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetStudentGender(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentGender(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentGender(System.IAsyncResult result) {
            string retVal = this.EndGetStudentGender(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentGenderCompleted(object state) {
            if ((this.GetStudentGenderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentGenderCompleted(this, new GetStudentGenderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentGenderAsync(string ID_No) {
            this.GetStudentGenderAsync(ID_No, null);
        }
        
        public void GetStudentGenderAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentGenderDelegate == null)) {
                this.onBeginGetStudentGenderDelegate = new BeginOperationDelegate(this.OnBeginGetStudentGender);
            }
            if ((this.onEndGetStudentGenderDelegate == null)) {
                this.onEndGetStudentGenderDelegate = new EndOperationDelegate(this.OnEndGetStudentGender);
            }
            if ((this.onGetStudentGenderCompletedDelegate == null)) {
                this.onGetStudentGenderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentGenderCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentGenderDelegate, new object[] {
                        ID_No}, this.onEndGetStudentGenderDelegate, this.onGetStudentGenderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginGetStudentMajor(HW2_WS_MobileClient.TomcatServices.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudentMajor(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetStudentMajor(string ID_No, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.GetStudentMajorRequest inValue = new HW2_WS_MobileClient.TomcatServices.GetStudentMajorRequest();
            inValue.ID_No = ID_No;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginGetStudentMajor(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndGetStudentMajor(System.IAsyncResult result) {
            return base.Channel.EndGetStudentMajor(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetStudentMajor(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndGetStudentMajor(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetStudentMajor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ID_No = ((string)(inValues[0]));
            return this.BeginGetStudentMajor(ID_No, callback, asyncState);
        }
        
        private object[] OnEndGetStudentMajor(System.IAsyncResult result) {
            string retVal = this.EndGetStudentMajor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentMajorCompleted(object state) {
            if ((this.GetStudentMajorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentMajorCompleted(this, new GetStudentMajorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentMajorAsync(string ID_No) {
            this.GetStudentMajorAsync(ID_No, null);
        }
        
        public void GetStudentMajorAsync(string ID_No, object userState) {
            if ((this.onBeginGetStudentMajorDelegate == null)) {
                this.onBeginGetStudentMajorDelegate = new BeginOperationDelegate(this.OnBeginGetStudentMajor);
            }
            if ((this.onEndGetStudentMajorDelegate == null)) {
                this.onEndGetStudentMajorDelegate = new EndOperationDelegate(this.OnEndGetStudentMajor);
            }
            if ((this.onGetStudentMajorCompletedDelegate == null)) {
                this.onGetStudentMajorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentMajorCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentMajorDelegate, new object[] {
                        ID_No}, this.onEndGetStudentMajorDelegate, this.onGetStudentMajorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.BeginInsertStudentInfo(HW2_WS_MobileClient.TomcatServices.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertStudentInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginInsertStudentInfo(string Info, System.AsyncCallback callback, object asyncState) {
            HW2_WS_MobileClient.TomcatServices.InsertStudentInfoRequest inValue = new HW2_WS_MobileClient.TomcatServices.InsertStudentInfoRequest();
            inValue.Info = Info;
            return ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).BeginInsertStudentInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType.EndInsertStudentInfo(System.IAsyncResult result) {
            return base.Channel.EndInsertStudentInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndInsertStudentInfo(System.IAsyncResult result) {
            HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse retVal = ((HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType)(this)).EndInsertStudentInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginInsertStudentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Info = ((string)(inValues[0]));
            return this.BeginInsertStudentInfo(Info, callback, asyncState);
        }
        
        private object[] OnEndInsertStudentInfo(System.IAsyncResult result) {
            string retVal = this.EndInsertStudentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertStudentInfoCompleted(object state) {
            if ((this.InsertStudentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertStudentInfoCompleted(this, new InsertStudentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertStudentInfoAsync(string Info) {
            this.InsertStudentInfoAsync(Info, null);
        }
        
        public void InsertStudentInfoAsync(string Info, object userState) {
            if ((this.onBeginInsertStudentInfoDelegate == null)) {
                this.onBeginInsertStudentInfoDelegate = new BeginOperationDelegate(this.OnBeginInsertStudentInfo);
            }
            if ((this.onEndInsertStudentInfoDelegate == null)) {
                this.onEndInsertStudentInfoDelegate = new EndOperationDelegate(this.OnEndInsertStudentInfo);
            }
            if ((this.onInsertStudentInfoCompletedDelegate == null)) {
                this.onInsertStudentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertStudentInfoCompleted);
            }
            base.InvokeAsync(this.onBeginInsertStudentInfoDelegate, new object[] {
                        Info}, this.onEndInsertStudentInfoDelegate, this.onInsertStudentInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType CreateChannel() {
            return new StuInfoWebServicePortTypeClientChannel(this);
        }
        
        private class StuInfoWebServicePortTypeClientChannel : ChannelBase<HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType>, HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType {
            
            public StuInfoWebServicePortTypeClientChannel(System.ServiceModel.ClientBase<HW2_WS_MobileClient.TomcatServices.StuInfoWebServicePortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDeleteStudentInfo(HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DeleteStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse EndDeleteStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse _result = ((HW2_WS_MobileClient.TomcatServices.DeleteStudentInfoResponse)(base.EndInvoke("DeleteStudentInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentEmailAddress(HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentEmailAddress", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse EndGetStudentEmailAddress(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse _result = ((HW2_WS_MobileClient.TomcatServices.GetStudentEmailAddressResponse)(base.EndInvoke("GetStudentEmailAddress", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateStudentInfo(HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse EndUpdateStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse _result = ((HW2_WS_MobileClient.TomcatServices.UpdateStudentInfoResponse)(base.EndInvoke("UpdateStudentInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentName(HW2_WS_MobileClient.TomcatServices.GetStudentNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentName", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse EndGetStudentName(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse _result = ((HW2_WS_MobileClient.TomcatServices.GetStudentNameResponse)(base.EndInvoke("GetStudentName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentGender(HW2_WS_MobileClient.TomcatServices.GetStudentGenderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentGender", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse EndGetStudentGender(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse _result = ((HW2_WS_MobileClient.TomcatServices.GetStudentGenderResponse)(base.EndInvoke("GetStudentGender", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStudentMajor(HW2_WS_MobileClient.TomcatServices.GetStudentMajorRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStudentMajor", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse EndGetStudentMajor(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse _result = ((HW2_WS_MobileClient.TomcatServices.GetStudentMajorResponse)(base.EndInvoke("GetStudentMajor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertStudentInfo(HW2_WS_MobileClient.TomcatServices.InsertStudentInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("InsertStudentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse EndInsertStudentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse _result = ((HW2_WS_MobileClient.TomcatServices.InsertStudentInfoResponse)(base.EndInvoke("InsertStudentInfo", _args, result)));
                return _result;
            }
        }
    }
}
