//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetTopClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ss.oku.edu.cn", ConfigurationName="ServiceReference1.Client")]
    public interface Client {
        
        // CODEGEN: Generating message contract since the operation initiate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.oku.edu.cn/initiate")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void initiate(SetTopClient.ServiceReference1.initiate request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.oku.edu.cn/initiate")]
        System.Threading.Tasks.Task initiateAsync(SetTopClient.ServiceReference1.initiate request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ss.oku.edu.cn")]
    public partial class ClientRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private int eventIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initiate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ss.oku.edu.cn", Order=0)]
        public SetTopClient.ServiceReference1.ClientRequest ClientRequest;
        
        public initiate() {
        }
        
        public initiate(SetTopClient.ServiceReference1.ClientRequest ClientRequest) {
            this.ClientRequest = ClientRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientChannel : SetTopClient.ServiceReference1.Client, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.Client>, SetTopClient.ServiceReference1.Client {
        
        public ClientClient() {
        }
        
        public ClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SetTopClient.ServiceReference1.Client.initiate(SetTopClient.ServiceReference1.initiate request) {
            base.Channel.initiate(request);
        }
        
        public void initiate(SetTopClient.ServiceReference1.ClientRequest ClientRequest) {
            SetTopClient.ServiceReference1.initiate inValue = new SetTopClient.ServiceReference1.initiate();
            inValue.ClientRequest = ClientRequest;
            ((SetTopClient.ServiceReference1.Client)(this)).initiate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SetTopClient.ServiceReference1.Client.initiateAsync(SetTopClient.ServiceReference1.initiate request) {
            return base.Channel.initiateAsync(request);
        }
        
        public System.Threading.Tasks.Task initiateAsync(SetTopClient.ServiceReference1.ClientRequest ClientRequest) {
            SetTopClient.ServiceReference1.initiate inValue = new SetTopClient.ServiceReference1.initiate();
            inValue.ClientRequest = ClientRequest;
            return ((SetTopClient.ServiceReference1.Client)(this)).initiateAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ss.oku.edu.cn", ConfigurationName="ServiceReference1.ClientCallback")]
    public interface ClientCallback {
        
        // CODEGEN: Generating message contract since the operation onResult is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.oku.edu.cn/onResult")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void onResult(SetTopClient.ServiceReference1.onResult request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.oku.edu.cn/onResult")]
        System.Threading.Tasks.Task onResultAsync(SetTopClient.ServiceReference1.onResult request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ss.oku.edu.cn")]
    public partial class ClientResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private int eventIDField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class onResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ss.oku.edu.cn", Order=0)]
        public SetTopClient.ServiceReference1.ClientResponse ClientResponse;
        
        public onResult() {
        }
        
        public onResult(SetTopClient.ServiceReference1.ClientResponse ClientResponse) {
            this.ClientResponse = ClientResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientCallbackChannel : SetTopClient.ServiceReference1.ClientCallback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientCallbackClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.ClientCallback>, SetTopClient.ServiceReference1.ClientCallback {
        
        public ClientCallbackClient() {
        }
        
        public ClientCallbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientCallbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientCallbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SetTopClient.ServiceReference1.ClientCallback.onResult(SetTopClient.ServiceReference1.onResult request) {
            base.Channel.onResult(request);
        }
        
        public void onResult(SetTopClient.ServiceReference1.ClientResponse ClientResponse) {
            SetTopClient.ServiceReference1.onResult inValue = new SetTopClient.ServiceReference1.onResult();
            inValue.ClientResponse = ClientResponse;
            ((SetTopClient.ServiceReference1.ClientCallback)(this)).onResult(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SetTopClient.ServiceReference1.ClientCallback.onResultAsync(SetTopClient.ServiceReference1.onResult request) {
            return base.Channel.onResultAsync(request);
        }
        
        public System.Threading.Tasks.Task onResultAsync(SetTopClient.ServiceReference1.ClientResponse ClientResponse) {
            SetTopClient.ServiceReference1.onResult inValue = new SetTopClient.ServiceReference1.onResult();
            inValue.ClientResponse = ClientResponse;
            return ((SetTopClient.ServiceReference1.ClientCallback)(this)).onResultAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ss.pku.edu.cn", ConfigurationName="ServiceReference1.CABLE_OPERATOR_PROCESS")]
    public interface CABLE_OPERATOR_PROCESS {
        
        // CODEGEN: Generating message contract since the operation initiate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.pku.edu.cn/initiate")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void initiate(SetTopClient.ServiceReference1.initiate1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.pku.edu.cn/initiate")]
        System.Threading.Tasks.Task initiateAsync(SetTopClient.ServiceReference1.initiate1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ss.pku.edu.cn")]
    public partial class CABLE_OPERATOR_PROCESSRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private int eventIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initiate1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ss.pku.edu.cn", Order=0)]
        public SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSRequest CABLE_OPERATOR_PROCESSRequest;
        
        public initiate1() {
        }
        
        public initiate1(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSRequest CABLE_OPERATOR_PROCESSRequest) {
            this.CABLE_OPERATOR_PROCESSRequest = CABLE_OPERATOR_PROCESSRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CABLE_OPERATOR_PROCESSChannel : SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CABLE_OPERATOR_PROCESSClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS>, SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS {
        
        public CABLE_OPERATOR_PROCESSClient() {
        }
        
        public CABLE_OPERATOR_PROCESSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CABLE_OPERATOR_PROCESSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CABLE_OPERATOR_PROCESSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CABLE_OPERATOR_PROCESSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS.initiate(SetTopClient.ServiceReference1.initiate1 request) {
            base.Channel.initiate(request);
        }
        
        public void initiate(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSRequest CABLE_OPERATOR_PROCESSRequest) {
            SetTopClient.ServiceReference1.initiate1 inValue = new SetTopClient.ServiceReference1.initiate1();
            inValue.CABLE_OPERATOR_PROCESSRequest = CABLE_OPERATOR_PROCESSRequest;
            ((SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS)(this)).initiate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS.initiateAsync(SetTopClient.ServiceReference1.initiate1 request) {
            return base.Channel.initiateAsync(request);
        }
        
        public System.Threading.Tasks.Task initiateAsync(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSRequest CABLE_OPERATOR_PROCESSRequest) {
            SetTopClient.ServiceReference1.initiate1 inValue = new SetTopClient.ServiceReference1.initiate1();
            inValue.CABLE_OPERATOR_PROCESSRequest = CABLE_OPERATOR_PROCESSRequest;
            return ((SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESS)(this)).initiateAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ss.pku.edu.cn", ConfigurationName="ServiceReference1.CABLE_OPERATOR_PROCESSCallback")]
    public interface CABLE_OPERATOR_PROCESSCallback {
        
        // CODEGEN: Generating message contract since the operation onResult is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.pku.edu.cn/onResult")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void onResult(SetTopClient.ServiceReference1.onResult1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ss.pku.edu.cn/onResult")]
        System.Threading.Tasks.Task onResultAsync(SetTopClient.ServiceReference1.onResult1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ss.pku.edu.cn")]
    public partial class CABLE_OPERATOR_PROCESSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private int eventIDField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("EventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class onResult1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ss.pku.edu.cn", Order=0)]
        public SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSResponse CABLE_OPERATOR_PROCESSResponse;
        
        public onResult1() {
        }
        
        public onResult1(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSResponse CABLE_OPERATOR_PROCESSResponse) {
            this.CABLE_OPERATOR_PROCESSResponse = CABLE_OPERATOR_PROCESSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CABLE_OPERATOR_PROCESSCallbackChannel : SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CABLE_OPERATOR_PROCESSCallbackClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback>, SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback {
        
        public CABLE_OPERATOR_PROCESSCallbackClient() {
        }
        
        public CABLE_OPERATOR_PROCESSCallbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CABLE_OPERATOR_PROCESSCallbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CABLE_OPERATOR_PROCESSCallbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CABLE_OPERATOR_PROCESSCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback.onResult(SetTopClient.ServiceReference1.onResult1 request) {
            base.Channel.onResult(request);
        }
        
        public void onResult(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSResponse CABLE_OPERATOR_PROCESSResponse) {
            SetTopClient.ServiceReference1.onResult1 inValue = new SetTopClient.ServiceReference1.onResult1();
            inValue.CABLE_OPERATOR_PROCESSResponse = CABLE_OPERATOR_PROCESSResponse;
            ((SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback)(this)).onResult(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback.onResultAsync(SetTopClient.ServiceReference1.onResult1 request) {
            return base.Channel.onResultAsync(request);
        }
        
        public System.Threading.Tasks.Task onResultAsync(SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSResponse CABLE_OPERATOR_PROCESSResponse) {
            SetTopClient.ServiceReference1.onResult1 inValue = new SetTopClient.ServiceReference1.onResult1();
            inValue.CABLE_OPERATOR_PROCESSResponse = CABLE_OPERATOR_PROCESSResponse;
            return ((SetTopClient.ServiceReference1.CABLE_OPERATOR_PROCESSCallback)(this)).onResultAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cn.edu.pku.ss.bank", ConfigurationName="ServiceReference1.BankService")]
    public interface BankService {
        
        // CODEGEN: Generating message contract since element name creditCardNo from namespace http://cn.edu.pku.ss.bank is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SetTopClient.ServiceReference1.creditCardAuthorizationResponse creditCardAuthorization(SetTopClient.ServiceReference1.creditCardAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.creditCardAuthorizationResponse> creditCardAuthorizationAsync(SetTopClient.ServiceReference1.creditCardAuthorizationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creditCardAuthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creditCardAuthorization", Namespace="http://cn.edu.pku.ss.bank", Order=0)]
        public SetTopClient.ServiceReference1.creditCardAuthorizationRequestBody Body;
        
        public creditCardAuthorizationRequest() {
        }
        
        public creditCardAuthorizationRequest(SetTopClient.ServiceReference1.creditCardAuthorizationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cn.edu.pku.ss.bank")]
    public partial class creditCardAuthorizationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creditCardNo;
        
        public creditCardAuthorizationRequestBody() {
        }
        
        public creditCardAuthorizationRequestBody(string creditCardNo) {
            this.creditCardNo = creditCardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class creditCardAuthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="creditCardAuthorizationResponse", Namespace="http://cn.edu.pku.ss.bank", Order=0)]
        public SetTopClient.ServiceReference1.creditCardAuthorizationResponseBody Body;
        
        public creditCardAuthorizationResponse() {
        }
        
        public creditCardAuthorizationResponse(SetTopClient.ServiceReference1.creditCardAuthorizationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cn.edu.pku.ss.bank")]
    public partial class creditCardAuthorizationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool creditCardAuthorizationReturn;
        
        public creditCardAuthorizationResponseBody() {
        }
        
        public creditCardAuthorizationResponseBody(bool creditCardAuthorizationReturn) {
            this.creditCardAuthorizationReturn = creditCardAuthorizationReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankServiceChannel : SetTopClient.ServiceReference1.BankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.BankService>, SetTopClient.ServiceReference1.BankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetTopClient.ServiceReference1.creditCardAuthorizationResponse SetTopClient.ServiceReference1.BankService.creditCardAuthorization(SetTopClient.ServiceReference1.creditCardAuthorizationRequest request) {
            return base.Channel.creditCardAuthorization(request);
        }
        
        public bool creditCardAuthorization(string creditCardNo) {
            SetTopClient.ServiceReference1.creditCardAuthorizationRequest inValue = new SetTopClient.ServiceReference1.creditCardAuthorizationRequest();
            inValue.Body = new SetTopClient.ServiceReference1.creditCardAuthorizationRequestBody();
            inValue.Body.creditCardNo = creditCardNo;
            SetTopClient.ServiceReference1.creditCardAuthorizationResponse retVal = ((SetTopClient.ServiceReference1.BankService)(this)).creditCardAuthorization(inValue);
            return retVal.Body.creditCardAuthorizationReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.creditCardAuthorizationResponse> SetTopClient.ServiceReference1.BankService.creditCardAuthorizationAsync(SetTopClient.ServiceReference1.creditCardAuthorizationRequest request) {
            return base.Channel.creditCardAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetTopClient.ServiceReference1.creditCardAuthorizationResponse> creditCardAuthorizationAsync(string creditCardNo) {
            SetTopClient.ServiceReference1.creditCardAuthorizationRequest inValue = new SetTopClient.ServiceReference1.creditCardAuthorizationRequest();
            inValue.Body = new SetTopClient.ServiceReference1.creditCardAuthorizationRequestBody();
            inValue.Body.creditCardNo = creditCardNo;
            return ((SetTopClient.ServiceReference1.BankService)(this)).creditCardAuthorizationAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CableServiceSoap")]
    public interface CableServiceSoap {
        
        // CODEGEN: Generating message contract since element name CustomerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCableInfo", ReplyAction="*")]
        SetTopClient.ServiceReference1.GetCableInfoResponse GetCableInfo(SetTopClient.ServiceReference1.GetCableInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCableInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.GetCableInfoResponse> GetCableInfoAsync(SetTopClient.ServiceReference1.GetCableInfoRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdCableInfo", ReplyAction="*")]
        SetTopClient.ServiceReference1.UpdCableInfoResponse UpdCableInfo(SetTopClient.ServiceReference1.UpdCableInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdCableInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.UpdCableInfoResponse> UpdCableInfoAsync(SetTopClient.ServiceReference1.UpdCableInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCableInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCableInfo", Namespace="http://tempuri.org/", Order=0)]
        public SetTopClient.ServiceReference1.GetCableInfoRequestBody Body;
        
        public GetCableInfoRequest() {
        }
        
        public GetCableInfoRequest(SetTopClient.ServiceReference1.GetCableInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCableInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int EventID;
        
        public GetCableInfoRequestBody() {
        }
        
        public GetCableInfoRequestBody(string CustomerID, int EventID) {
            this.CustomerID = CustomerID;
            this.EventID = EventID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCableInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCableInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetTopClient.ServiceReference1.GetCableInfoResponseBody Body;
        
        public GetCableInfoResponse() {
        }
        
        public GetCableInfoResponse(SetTopClient.ServiceReference1.GetCableInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCableInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCableInfoResult;
        
        public GetCableInfoResponseBody() {
        }
        
        public GetCableInfoResponseBody(string GetCableInfoResult) {
            this.GetCableInfoResult = GetCableInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdCableInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdCableInfo", Namespace="http://tempuri.org/", Order=0)]
        public SetTopClient.ServiceReference1.UpdCableInfoRequestBody Body;
        
        public UpdCableInfoRequest() {
        }
        
        public UpdCableInfoRequest(SetTopClient.ServiceReference1.UpdCableInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdCableInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int EventID;
        
        public UpdCableInfoRequestBody() {
        }
        
        public UpdCableInfoRequestBody(string CustomerID, int EventID) {
            this.CustomerID = CustomerID;
            this.EventID = EventID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdCableInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdCableInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetTopClient.ServiceReference1.UpdCableInfoResponseBody Body;
        
        public UpdCableInfoResponse() {
        }
        
        public UpdCableInfoResponse(SetTopClient.ServiceReference1.UpdCableInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdCableInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdCableInfoResult;
        
        public UpdCableInfoResponseBody() {
        }
        
        public UpdCableInfoResponseBody(string UpdCableInfoResult) {
            this.UpdCableInfoResult = UpdCableInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CableServiceSoapChannel : SetTopClient.ServiceReference1.CableServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CableServiceSoapClient : System.ServiceModel.ClientBase<SetTopClient.ServiceReference1.CableServiceSoap>, SetTopClient.ServiceReference1.CableServiceSoap {
        
        public CableServiceSoapClient() {
        }
        
        public CableServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CableServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CableServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CableServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetTopClient.ServiceReference1.GetCableInfoResponse SetTopClient.ServiceReference1.CableServiceSoap.GetCableInfo(SetTopClient.ServiceReference1.GetCableInfoRequest request) {
            return base.Channel.GetCableInfo(request);
        }
        
        public string GetCableInfo(string CustomerID, int EventID) {
            SetTopClient.ServiceReference1.GetCableInfoRequest inValue = new SetTopClient.ServiceReference1.GetCableInfoRequest();
            inValue.Body = new SetTopClient.ServiceReference1.GetCableInfoRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EventID = EventID;
            SetTopClient.ServiceReference1.GetCableInfoResponse retVal = ((SetTopClient.ServiceReference1.CableServiceSoap)(this)).GetCableInfo(inValue);
            return retVal.Body.GetCableInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.GetCableInfoResponse> SetTopClient.ServiceReference1.CableServiceSoap.GetCableInfoAsync(SetTopClient.ServiceReference1.GetCableInfoRequest request) {
            return base.Channel.GetCableInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetTopClient.ServiceReference1.GetCableInfoResponse> GetCableInfoAsync(string CustomerID, int EventID) {
            SetTopClient.ServiceReference1.GetCableInfoRequest inValue = new SetTopClient.ServiceReference1.GetCableInfoRequest();
            inValue.Body = new SetTopClient.ServiceReference1.GetCableInfoRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EventID = EventID;
            return ((SetTopClient.ServiceReference1.CableServiceSoap)(this)).GetCableInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetTopClient.ServiceReference1.UpdCableInfoResponse SetTopClient.ServiceReference1.CableServiceSoap.UpdCableInfo(SetTopClient.ServiceReference1.UpdCableInfoRequest request) {
            return base.Channel.UpdCableInfo(request);
        }
        
        public string UpdCableInfo(string CustomerID, int EventID) {
            SetTopClient.ServiceReference1.UpdCableInfoRequest inValue = new SetTopClient.ServiceReference1.UpdCableInfoRequest();
            inValue.Body = new SetTopClient.ServiceReference1.UpdCableInfoRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EventID = EventID;
            SetTopClient.ServiceReference1.UpdCableInfoResponse retVal = ((SetTopClient.ServiceReference1.CableServiceSoap)(this)).UpdCableInfo(inValue);
            return retVal.Body.UpdCableInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetTopClient.ServiceReference1.UpdCableInfoResponse> SetTopClient.ServiceReference1.CableServiceSoap.UpdCableInfoAsync(SetTopClient.ServiceReference1.UpdCableInfoRequest request) {
            return base.Channel.UpdCableInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetTopClient.ServiceReference1.UpdCableInfoResponse> UpdCableInfoAsync(string CustomerID, int EventID) {
            SetTopClient.ServiceReference1.UpdCableInfoRequest inValue = new SetTopClient.ServiceReference1.UpdCableInfoRequest();
            inValue.Body = new SetTopClient.ServiceReference1.UpdCableInfoRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EventID = EventID;
            return ((SetTopClient.ServiceReference1.CableServiceSoap)(this)).UpdCableInfoAsync(inValue);
        }
    }
}
