//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPEL_Client.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://correlation.bpel.tps", ConfigurationName="ServiceReference3.BPEL_LOANPortType")]
    public interface BPEL_LOANPortType {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://correlation.bpel.tps/process", ReplyAction="http://correlation.bpel.tps/BPEL_LOAN/processResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPEL_Client.ServiceReference3.processResponse process(BPEL_Client.ServiceReference3.processRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correlation.bpel.tps")]
    public partial class BPEL_LOANRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private double moneyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double money {
            get {
                return this.moneyField;
            }
            set {
                this.moneyField = value;
                this.RaisePropertyChanged("money");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correlation.bpel.tps")]
    public partial class BPEL_LOANResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://correlation.bpel.tps", Order=0)]
        public BPEL_Client.ServiceReference3.BPEL_LOANRequest BPEL_LOANRequest;
        
        public processRequest() {
        }
        
        public processRequest(BPEL_Client.ServiceReference3.BPEL_LOANRequest BPEL_LOANRequest) {
            this.BPEL_LOANRequest = BPEL_LOANRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://correlation.bpel.tps", Order=0)]
        public BPEL_Client.ServiceReference3.BPEL_LOANResponse BPEL_LOANResponse;
        
        public processResponse() {
        }
        
        public processResponse(BPEL_Client.ServiceReference3.BPEL_LOANResponse BPEL_LOANResponse) {
            this.BPEL_LOANResponse = BPEL_LOANResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BPEL_LOANPortTypeChannel : BPEL_Client.ServiceReference3.BPEL_LOANPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BPEL_LOANPortTypeClient : System.ServiceModel.ClientBase<BPEL_Client.ServiceReference3.BPEL_LOANPortType>, BPEL_Client.ServiceReference3.BPEL_LOANPortType {
        
        public BPEL_LOANPortTypeClient() {
        }
        
        public BPEL_LOANPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BPEL_LOANPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPEL_LOANPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPEL_LOANPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPEL_Client.ServiceReference3.processResponse BPEL_Client.ServiceReference3.BPEL_LOANPortType.process(BPEL_Client.ServiceReference3.processRequest request) {
            return base.Channel.process(request);
        }
        
        public BPEL_Client.ServiceReference3.BPEL_LOANResponse process(BPEL_Client.ServiceReference3.BPEL_LOANRequest BPEL_LOANRequest) {
            BPEL_Client.ServiceReference3.processRequest inValue = new BPEL_Client.ServiceReference3.processRequest();
            inValue.BPEL_LOANRequest = BPEL_LOANRequest;
            BPEL_Client.ServiceReference3.processResponse retVal = ((BPEL_Client.ServiceReference3.BPEL_LOANPortType)(this)).process(inValue);
            return retVal.BPEL_LOANResponse;
        }
    }
}
