//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace DinnerDecisionPlus.AzureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AzureService.TestSoap")]
    public interface TestSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(DinnerDecisionPlus.AzureService.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        DinnerDecisionPlus.AzureService.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetRestaurant", ReplyAction="*")]
        System.IAsyncResult BeginGetRestaurant(DinnerDecisionPlus.AzureService.GetRestaurantRequest request, System.AsyncCallback callback, object asyncState);
        
        DinnerDecisionPlus.AzureService.GetRestaurantResponse EndGetRestaurant(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DinnerDecisionPlus.AzureService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DinnerDecisionPlus.AzureService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DinnerDecisionPlus.AzureService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DinnerDecisionPlus.AzureService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public DinnerDecisionPlus.AzureService.GetRestaurantRequestBody Body;
        
        public GetRestaurantRequest() {
        }
        
        public GetRestaurantRequest(DinnerDecisionPlus.AzureService.GetRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestaurantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double longitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double r;
        
        public GetRestaurantRequestBody() {
        }
        
        public GetRestaurantRequestBody(double latitude, double longitude, double r) {
            this.latitude = latitude;
            this.longitude = longitude;
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public DinnerDecisionPlus.AzureService.GetRestaurantResponseBody Body;
        
        public GetRestaurantResponse() {
        }
        
        public GetRestaurantResponse(DinnerDecisionPlus.AzureService.GetRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRestaurantResult;
        
        public GetRestaurantResponseBody() {
        }
        
        public GetRestaurantResponseBody(string GetRestaurantResult) {
            this.GetRestaurantResult = GetRestaurantResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestSoapChannel : DinnerDecisionPlus.AzureService.TestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestSoapClient : System.ServiceModel.ClientBase<DinnerDecisionPlus.AzureService.TestSoap>, DinnerDecisionPlus.AzureService.TestSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRestaurantDelegate;
        
        private EndOperationDelegate onEndGetRestaurantDelegate;
        
        private System.Threading.SendOrPostCallback onGetRestaurantCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TestSoapClient() {
        }
        
        public TestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetRestaurantCompletedEventArgs> GetRestaurantCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DinnerDecisionPlus.AzureService.TestSoap.BeginHelloWorld(DinnerDecisionPlus.AzureService.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(string name, System.AsyncCallback callback, object asyncState) {
            DinnerDecisionPlus.AzureService.HelloWorldRequest inValue = new DinnerDecisionPlus.AzureService.HelloWorldRequest();
            inValue.Body = new DinnerDecisionPlus.AzureService.HelloWorldRequestBody();
            inValue.Body.name = name;
            return ((DinnerDecisionPlus.AzureService.TestSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinnerDecisionPlus.AzureService.HelloWorldResponse DinnerDecisionPlus.AzureService.TestSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            DinnerDecisionPlus.AzureService.HelloWorldResponse retVal = ((DinnerDecisionPlus.AzureService.TestSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return this.BeginHelloWorld(name, callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync(string name) {
            this.HelloWorldAsync(name, null);
        }
        
        public void HelloWorldAsync(string name, object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, new object[] {
                        name}, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DinnerDecisionPlus.AzureService.TestSoap.BeginGetRestaurant(DinnerDecisionPlus.AzureService.GetRestaurantRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRestaurant(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRestaurant(double latitude, double longitude, double r, System.AsyncCallback callback, object asyncState) {
            DinnerDecisionPlus.AzureService.GetRestaurantRequest inValue = new DinnerDecisionPlus.AzureService.GetRestaurantRequest();
            inValue.Body = new DinnerDecisionPlus.AzureService.GetRestaurantRequestBody();
            inValue.Body.latitude = latitude;
            inValue.Body.longitude = longitude;
            inValue.Body.r = r;
            return ((DinnerDecisionPlus.AzureService.TestSoap)(this)).BeginGetRestaurant(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinnerDecisionPlus.AzureService.GetRestaurantResponse DinnerDecisionPlus.AzureService.TestSoap.EndGetRestaurant(System.IAsyncResult result) {
            return base.Channel.EndGetRestaurant(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetRestaurant(System.IAsyncResult result) {
            DinnerDecisionPlus.AzureService.GetRestaurantResponse retVal = ((DinnerDecisionPlus.AzureService.TestSoap)(this)).EndGetRestaurant(result);
            return retVal.Body.GetRestaurantResult;
        }
        
        private System.IAsyncResult OnBeginGetRestaurant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double latitude = ((double)(inValues[0]));
            double longitude = ((double)(inValues[1]));
            double r = ((double)(inValues[2]));
            return this.BeginGetRestaurant(latitude, longitude, r, callback, asyncState);
        }
        
        private object[] OnEndGetRestaurant(System.IAsyncResult result) {
            string retVal = this.EndGetRestaurant(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRestaurantCompleted(object state) {
            if ((this.GetRestaurantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRestaurantCompleted(this, new GetRestaurantCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRestaurantAsync(double latitude, double longitude, double r) {
            this.GetRestaurantAsync(latitude, longitude, r, null);
        }
        
        public void GetRestaurantAsync(double latitude, double longitude, double r, object userState) {
            if ((this.onBeginGetRestaurantDelegate == null)) {
                this.onBeginGetRestaurantDelegate = new BeginOperationDelegate(this.OnBeginGetRestaurant);
            }
            if ((this.onEndGetRestaurantDelegate == null)) {
                this.onEndGetRestaurantDelegate = new EndOperationDelegate(this.OnEndGetRestaurant);
            }
            if ((this.onGetRestaurantCompletedDelegate == null)) {
                this.onGetRestaurantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRestaurantCompleted);
            }
            base.InvokeAsync(this.onBeginGetRestaurantDelegate, new object[] {
                        latitude,
                        longitude,
                        r}, this.onEndGetRestaurantDelegate, this.onGetRestaurantCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DinnerDecisionPlus.AzureService.TestSoap CreateChannel() {
            return new TestSoapClientChannel(this);
        }
        
        private class TestSoapClientChannel : ChannelBase<DinnerDecisionPlus.AzureService.TestSoap>, DinnerDecisionPlus.AzureService.TestSoap {
            
            public TestSoapClientChannel(System.ServiceModel.ClientBase<DinnerDecisionPlus.AzureService.TestSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(DinnerDecisionPlus.AzureService.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public DinnerDecisionPlus.AzureService.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                DinnerDecisionPlus.AzureService.HelloWorldResponse _result = ((DinnerDecisionPlus.AzureService.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRestaurant(DinnerDecisionPlus.AzureService.GetRestaurantRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRestaurant", _args, callback, asyncState);
                return _result;
            }
            
            public DinnerDecisionPlus.AzureService.GetRestaurantResponse EndGetRestaurant(System.IAsyncResult result) {
                object[] _args = new object[0];
                DinnerDecisionPlus.AzureService.GetRestaurantResponse _result = ((DinnerDecisionPlus.AzureService.GetRestaurantResponse)(base.EndInvoke("GetRestaurant", _args, result)));
                return _result;
            }
        }
    }
}
