//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPEL_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://correlation.bpel.tps", ConfigurationName="ServiceReference1.CorrelationPortType")]
    public interface CorrelationPortType {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://correlation.bpel.tps/process", ReplyAction="http://correlation.bpel.tps/Correlation/processResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPEL_Client.ServiceReference1.processResponse process(BPEL_Client.ServiceReference1.processRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correlation.bpel.tps")]
    public partial class CorrelationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double inputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("input");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://correlation.bpel.tps")]
    public partial class CorrelationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://correlation.bpel.tps", Order=0)]
        public BPEL_Client.ServiceReference1.CorrelationRequest CorrelationRequest;
        
        public processRequest() {
        }
        
        public processRequest(BPEL_Client.ServiceReference1.CorrelationRequest CorrelationRequest) {
            this.CorrelationRequest = CorrelationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://correlation.bpel.tps", Order=0)]
        public BPEL_Client.ServiceReference1.CorrelationResponse CorrelationResponse;
        
        public processResponse() {
        }
        
        public processResponse(BPEL_Client.ServiceReference1.CorrelationResponse CorrelationResponse) {
            this.CorrelationResponse = CorrelationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorrelationPortTypeChannel : BPEL_Client.ServiceReference1.CorrelationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorrelationPortTypeClient : System.ServiceModel.ClientBase<BPEL_Client.ServiceReference1.CorrelationPortType>, BPEL_Client.ServiceReference1.CorrelationPortType {
        
        public CorrelationPortTypeClient() {
        }
        
        public CorrelationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorrelationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrelationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrelationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPEL_Client.ServiceReference1.processResponse BPEL_Client.ServiceReference1.CorrelationPortType.process(BPEL_Client.ServiceReference1.processRequest request) {
            return base.Channel.process(request);
        }
        
        public BPEL_Client.ServiceReference1.CorrelationResponse process(BPEL_Client.ServiceReference1.CorrelationRequest CorrelationRequest) {
            BPEL_Client.ServiceReference1.processRequest inValue = new BPEL_Client.ServiceReference1.processRequest();
            inValue.CorrelationRequest = CorrelationRequest;
            BPEL_Client.ServiceReference1.processResponse retVal = ((BPEL_Client.ServiceReference1.CorrelationPortType)(this)).process(inValue);
            return retVal.CorrelationResponse;
        }
    }
}
